# -*- coding: utf-8 -*-
"""neuroplasticity_sem_rf_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dyuehRhrNi03AlcdiEP_C7bl-Fluv1xv
"""

import pandas as pd

df= pd.read_csv('neuroplasticity_survey_data.csv')
print(df)

import pandas as pd

df= pd.read_csv('neuroplasticity_survey_data.csv')
df= df.drop(['Timestamp', 'Email Address'], axis=1)

df.columns= df.columns.str.strip()
df= df.apply(lambda x: x.str.strip() if x.dtype == 'object' else x)

likert_maps= {
    'Strongly Disagree': 1,
    'Disagree': 2,
    'Neutral': 3,
    'Agree': 4,
    'Strongly Agree': 5
}

freq_map= {
    'Never': 1,
    'Not at all': 1,
    'A little': 2,
    'Ocassionally': 2,
    'Sometimes': 3,
    'Often': 4,
    'Mostly': 4,
    'Extremely': 5,
    'Always': 5
}

sleep_map= {
    'Less than 4': 3,
    '4-5': 4.5,
    '6-7': 6.5,
    '8 or more': 8.5
}

screen_map= {
    'Less than 2 hours': 1,
    '2-4 hours': 3,
    '4-6 hours': 5,
    '6-8 hours': 7,
    'More than 8 hours': 10
}

junk_food_map = {
    'Never': 1,
    '1-2 times/week': 2,
    '3-4 times/week': 3,
    '5-6 times/week': 4,
    'Every day': 5
}

likert_cols= ['cog_engage1', 'cog_engage2', 'cog_engage3', 'cog_engage4', 'learning1', 'learning2',
              'performance_reflects_potential', 'responsibilities_interfere','creative_activities_benefits', 'doomscroll_exhaust',
              'multitask_check_phone', 'multitask_notifications', 'sedentary_behavior1', 'sedentary_behavior2']

freq_cols= ['exercise_improve_cognition', 'exercise_regulate_emotion', 'nature_improve', 'nutritional_balanced_freq', 'nutritional_mood_focus']

for col in likert_cols:
  df[col + '_num'] = df[col].map(likert_maps)

for col in freq_cols:
  df[col + '_num'] = df[col].map(freq_map)

df['junk_food_freq_num'] = df['junk_food_freq'].map(junk_food_map)

df['sleep_hours_num'] = df['sleep_hours'].map(sleep_map)
df['screen_hours_num'] = df['screen_time'].map(screen_map)

df.to_csv('neuroplasticity_survey_data_cleaned.csv', index=False)
print(df)

!pip install semopy

import pandas as pd
data = pd.read_csv('neuroplasticity_survey_data_cleaned.csv')

data['cognitive_engagement'] = data[['cog_engage1_num','cog_engage2_num','cog_engage3_num','cog_engage4_num']].mean(axis=1)

data['academic_performance'] = data[['learning1_num','learning2_num','performance_reflects_potential_num']].mean(axis=1)

data['neuroplasticity'] = data[['sleep_hours_num','exercise_improve_cognition_num',
                               'nutritional_balanced_freq_num','screen_hours_num']].mean(axis=1)

from semopy import Model

model_desc = """
# Measurement (if using composites, skip latent part)

# Structural model
cognitive_engagement ~ neuroplasticity
academic_performance ~ cognitive_engagement + neuroplasticity
"""

model = Model(model_desc)

from semopy import Model

model_desc = """
# Measurement (if using composites, skip latent part)

# Structural model
cognitive_engagement ~ neuroplasticity
academic_performance ~ cognitive_engagement + neuroplasticity
"""

model = Model(model_desc)
model.fit(data)

# Results
results = model.inspect()
print(results)

from semopy import calc_stats

stats = calc_stats(model)
print(stats)

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

X = data[['sleep_hours_num','screen_hours_num','doomscroll_exhaust_num',
          'cognitive_engagement','exercise_improve_cognition_num']]

y = data['academic_performance']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestRegressor(n_estimators=100)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
r_squared = model.score(X_test, y_test)

print(f"R-squared on the test set: {r_squared:.2f}")